Public Class ribbonThemeDark
    Inherits RibbonProfesionalRendererColorTable

    Private highlight As String = "#335463" '"#E5C365"
    Private backgroundColor As String = "#000000" '"#272822"
    Private lightGray As String = "#D0D0D0"
    Private medGray As String = "#757575"
    Private textColor As String = "#F8F8F2"

    Public Sub New()
        OrbDropDownDarkBorder = FromHex(backgroundColor)
        OrbDropDownLightBorder = FromHex(textColor)
        OrbDropDownBack = FromHex(backgroundColor)
        OrbDropDownNorthA = FromHex(backgroundColor)
        OrbDropDownNorthB = FromHex(backgroundColor)
        OrbDropDownNorthC = FromHex(backgroundColor)
        OrbDropDownNorthD = FromHex(backgroundColor)
        OrbDropDownSouthC = FromHex(backgroundColor)
        OrbDropDownSouthD = FromHex(backgroundColor)
        OrbDropDownContentbg = FromHex(backgroundColor)
        OrbDropDownContentbglight = FromHex(backgroundColor)
        OrbDropDownSeparatorlight = FromHex(textColor)
        OrbDropDownSeparatordark = FromHex(backgroundColor)
        Caption1 = FromHex(lightGray)
        Caption2 = FromHex(lightGray)
        Caption3 = FromHex(lightGray)
        Caption4 = FromHex(lightGray)
        Caption5 = FromHex(lightGray)
        Caption6 = FromHex(lightGray)
        Caption7 = FromHex(lightGray)
        QuickAccessBorderDark = FromHex(backgroundColor)
        QuickAccessBorderLight = FromHex(lightGray)
        QuickAccessUpper = FromHex(medGray)
        QuickAccessLower = FromHex(medGray)
        OrbOptionBorder = FromHex(lightGray)
        OrbOptionBackground = FromHex(medGray)
        OrbOptionShine = FromHex(medGray)
        Arrow = FromHex(medGray)
        ArrowLight = FromHex(lightGray)
        ArrowDisabled = FromHex("#B7B7B7")
        Text = FromHex(textColor)
        RibbonBackground = FromHex(backgroundColor)
        TabBorder = FromHex(textColor)

        TabNorth = FromHex(highlight)
        TabSouth = FromHex(highlight)
        TabGlow = FromHex(highlight)
        TabText = FromHex(textColor)

        TabActiveText = FromHex(backgroundColor)
        TabContentNorth = FromHex(medGray)
        TabContentSouth = FromHex("#B7B7B7")
        TabSelectedGlow = FromHex(highlight)
        PanelDarkBorder = FromHex(medGray)
        PanelLightBorder = FromHex(lightGray)
        PanelTextBackground = FromHex(backgroundColor)
        PanelTextBackgroundSelected = FromHex(medGray)
        PanelText = FromHex(textColor)
        PanelBackgroundSelected = FromHex(medGray)
        PanelOverflowBackground = FromHex(highlight)
        PanelOverflowBackgroundPressed = FromHex(highlight)
        PanelOverflowBackgroundSelectedNorth = FromHex(medGray)
        PanelOverflowBackgroundSelectedSouth = FromHex(medGray)

        ButtonBgOut = FromHex(medGray)
        ButtonBgCenter = FromHex(backgroundColor)
        ButtonBorderOut = FromHex(lightGray)
        ButtonBorderIn = FromHex(medGray)
        ButtonGlossyNorth = FromHex(lightGray)
        ButtonGlossySouth = FromHex(medGray)

        ButtonDisabledBgOut = FromHex(medGray)
        ButtonDisabledBgCenter = FromHex(medGray)
        ButtonDisabledBorderOut = FromHex(lightGray)
        ButtonDisabledBorderIn = FromHex(medGray)
        ButtonDisabledGlossyNorth = FromHex(lightGray)
        ButtonDisabledGlossySouth = FromHex(lightGray)

        ButtonSelectedBgOut = FromHex(medGray)
        ButtonSelectedBgCenter = FromHex(backgroundColor)
        ButtonSelectedBorderOut = FromHex(medGray)
        ButtonSelectedBorderIn = FromHex(medGray)
        ButtonSelectedGlossyNorth = FromHex(lightGray)
        ButtonSelectedGlossySouth = FromHex(medGray)

        ButtonPressedBgOut = FromHex(medGray)
        ButtonPressedBgCenter = FromHex(backgroundColor)
        ButtonPressedBorderOut = FromHex(lightGray)
        ButtonPressedBorderIn = FromHex(medGray)
        ButtonPressedGlossyNorth = FromHex(lightGray)
        ButtonPressedGlossySouth = FromHex(medGray)

        ButtonCheckedBgOut = FromHex(medGray)
        ButtonCheckedBgCenter = FromHex(backgroundColor)
        ButtonCheckedBorderOut = FromHex(lightGray)
        ButtonCheckedBorderIn = FromHex(medGray)
        ButtonCheckedGlossyNorth = FromHex(lightGray)
        ButtonCheckedGlossySouth = FromHex(medGray)

        ItemGroupOuterBorder = FromHex(lightGray)
        ItemGroupInnerBorder = FromHex(medGray)
        ItemGroupSeparatorLight = FromHex(lightGray)
        ItemGroupSeparatorDark = FromHex(medGray)
        ItemGroupBgNorth = FromHex(backgroundColor)
        ItemGroupBgSouth = FromHex(backgroundColor)
        ItemGroupBgGlossy = FromHex(medGray)
        ButtonListBorder = FromHex(lightGray)
        ButtonListBg = FromHex(backgroundColor)
        ButtonListBgSelected = FromHex(lightGray)
        DropDownBg = FromHex(backgroundColor)
        DropDownImageBg = FromHex(backgroundColor)
        DropDownImageSeparator = FromHex(lightGray)
        DropDownBorder = FromHex(lightGray)
        DropDownGripNorth = FromHex(lightGray)
        DropDownGripSouth = FromHex(lightGray)
        DropDownGripBorder = FromHex(medGray)
        DropDownGripDark = FromHex(backgroundColor)
        DropDownGripLight = FromHex(textColor)
        SeparatorLight = FromHex(lightGray)
        SeparatorDark = FromHex(medGray)
        SeparatorBg = FromHex(backgroundColor)
        SeparatorLine = FromHex(medGray)
        TextBoxUnselectedBg = FromHex(medGray)
        TextBoxBorder = FromHex(lightGray)
        ToolTipContentNorth = FromHex(medGray)
        ToolTipContentSouth = FromHex(backgroundColor)
        ToolTipDarkBorder = FromHex(medGray)
        ToolTipLightBorder = FromHex(lightGray)
        ToolStripItemTextPressed = FromHex(backgroundColor)
        ToolStripItemTextSelected = FromHex(backgroundColor)
        ToolStripItemText = FromHex(backgroundColor)
        clrVerBG_Shadow = FromHex("#FFFFFF")

        ButtonPressed_2013 = FromHex(highlight)
        ButtonSelected_2013 = FromHex(highlight)
        OrbButton_2013 = FromHex(highlight)
        OrbButtonSelected_2013 = FromHex(highlight)
        OrbButtonPressed_2013 = FromHex(highlight)

        TabText_2013 = FromHex(textColor) 'FromHex(medGray)
        TabTextSelected_2013 = FromHex(textColor)

        PanelBorder_2013 = FromHex(medGray)
        RibbonBackground_2013 = FromHex(backgroundColor)
        TabCompleteBackground_2013 = FromHex(backgroundColor)
        TabNormalBackground_2013 = FromHex(backgroundColor)
        TabActiveBackbround_2013 = FromHex(highlight)
        TabBorder_2013 = FromHex(medGray)
        TabCompleteBorder_2013 = FromHex(medGray)
        TabActiveBorder_2013 = FromHex(highlight)
        OrbButtonText_2013 = FromHex(backgroundColor)
        PanelText_2013 = FromHex(textColor)
        RibbonItemText_2013 = FromHex(textColor)
        ToolTipText_2013 = FromHex(textColor)
        ToolStripItemTextPressed_2013 = FromHex(medGray)
        ToolStripItemTextSelected_2013 = FromHex(medGray)
        ToolStripItemText_2013 = FromHex(textColor)
    End Sub

    Public Overloads Function FromHex(ByVal hex As String) As Color
        If hex.StartsWith("#") Then
            hex = hex.Substring(1)
        End If
        If hex.Length <> 6 Then Throw New Exception("Invalid Color")

        Return Color.FromArgb(Integer.Parse(hex.Substring(0, 2), System.Globalization.NumberStyles.HexNumber), _
            Integer.Parse(hex.Substring(2, 2), System.Globalization.NumberStyles.HexNumber), _
            Integer.Parse(hex.Substring(4, 2), System.Globalization.NumberStyles.HexNumber))
    End Function

End Class
